### PR TITLE
Define cleanup

### PR DESCRIPTION
**Pull request by CalebMorris**
Working through files moving defined constants to `enum` or `static const <type>`

### CODE REVIEW

**Comment by andrewrk** [comment]
we're working in the it-is-time branch. want to rebase and see if it merges into that branch?

you're likely to get a lot of conflicts.

**Comment by CalebMorris** [comment]
I assumed that was the working branch, but it currently doesn't build for me.
I'll start on that branch once I can get stuff up.

**Comment by andrewrk** [comment]
It's not building for us either, hence the branch. Working on it

**Comment by thejoshwolfe** [comment]
fyi. the it-is-time branch builds, but everything's broken at runtime. it'll be a while before this game is playable again.

**Comment by CalebMorris** [comment]
Cool.
Do you guys have any kind of roadmap on what changes you plan to go through first?

**Pull request closed without merging**
