### PR TITLE
Define macro to funcs

### PR DESCRIPTION
**Pull request by CalebMorris**

### CODE REVIEW

**Comment by thejoshwolfe** [comment]
you're a contributor to this repo. why don't you come on over and push directly?

**Comment by CalebMorris** [comment]
Because I prefer the PR stile commit sharing to have a little extra sanity check.
I have a lot of bad habbits with using rebase and force pushing and accidently wiped a repo that wasn't restricted before :cry:

**Comment by thejoshwolfe** [comment]
don't force push?

also, why don't you just work in a branch then? that way we can be checking your work as soon as you're pushing.

**Comment by andrewrk** [comment]
nice

**Pull request merged**
